name "ri_opsworks"
maintainer "RawIron"
description "opsworks utils"
license "Apache 2.0"
version "0.1"

depends "ri_cloud"
depends "ri_deploy"
depends "ri_python_django"
depends "ri_gatling"
depends "ri_uwsgi"